[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ccwc"
version = "0.0.1"
requires-python = ">= 3.11"
authors =[
    {name = "Aaron Elmquist"},
]
description = "python based wc"

[project.scripts]
ccwc = "ccwc.cli:app"